sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge Group-19
  - docker pull mongo
  - docker run -d --name mongo-groupdb --network Group-19 mongo
  - docker build -t SEM-Group19 .
  - docker run --network Group-19 SEM-Group19